### ISSUE TITLE
[1.10] No more sprout drops

### ISSUE THREAD

**Issue by MachinegunMarty** [xLionel775/AgriculturalExpansion#10]
If i harvest a crop it only drops essences and no sprouts.
Is this intended ?

I harvested over a 100 crops of diamonds and such and not one dropped a sprout.

AgriculturalExpansion[1.10]-beta 1.1.13
forge-1.10-12.18.0.1996

**Comment by ionelaipatioaei** [comment]
I checked this in Minecraft 1.10 and I had no problem. Do you still have the problem?

**Comment by MachinegunMarty** [comment]
Yes, still have the problem.

**Comment by MachinegunMarty** [comment]
forge-1.10-12.18.0.2000
AgriculturalExpansion[1.10]-beta 1.1.13

Hope this helps:

I have the option bonemeal true and i use a mooshroom pet (inventory pets) to bonemeal them and i have mike dongles installed for right click harvest.

But i have tried with the bonemeal option off, and that to didn't give me a sprout.

The only way i seem to get a sprout is when i left  click the crop. It gives me the crop back + a chance on a extra sprout.
I figured this out because i had to move the plants to a new location. 
I moved  all of my 14 crops and 2 gave me an extra sprout i noticed later.

I have removed a couple of mods that i thought where interfering, but it still doesn't give me a sprout.

Mods i removed:
Reliquery (had mob drops events that i thought were interfering)
Blood Arsenal (A recipe error and event)
Mystical Crops (Thought maybe because you use the same essence name..)
Better Agriculture (Animals weren't dropping chunks anymore. Maybe because it adjusts animal names)
tconstruct (sword causes server crash when killing skeleton)

And i keep my mods and forge updated (sometimes 3 times a day)

So the reports i send you are with the latest forge version and mod versions.

I really like your mod, so any help i can offer i will.

Thanx for making a awesome mod !

grtz,

Machinegun_Marty

**Comment by ionelaipatioaei** [comment]
I can assure you that Reliquery, Blood Arsenal, Mystical Crops or tconstruct doesn't cause the problem. Better Agriculture may cause a problem with animal chunks but nothing else(maybe I will add compatibility with this mod). I tested the crops with mike dongles and I had no issue with them. Also I use canUseBonemeal set to true for testing the new crops so no issue there. Can you give me a full list with mods that you are using?

**Comment by MachinegunMarty** [comment]
Yeah, but just to be sure that something wasn't messing up. 
I'm testing on my private server to see which mods work on 1.10 and trying to help out the mod makers by sending in error reports.
You mod makers are doing an awesome job so i try to help where i can by sending in error reports, but i have a lot of mods and i try to help all of you.

I just wanted to tell you i did some testing of my own:

I made a single player creative world -->   tried with a coal sprout and bonemeal --> no sprouts, just essences.

Tried removing mike dongles and using my old one (Simple Harvest) --> no sprout
Tried replacing Simple harvest with no Reap --> no sprout

Just did some more testing on my server to see if i can reproduce the left click gives sprout trick:

I left clicked a mature coal crops and it dropped: 1 essence + 2 sprouts
Replanted 1 sprout and on 0% left clicked it: gave me the sprout back
Replanted 1 sprout and on 30% left clicked it: gave me the sprout back

Here's comes the wut:
Replanted 1 sprout and on "Mature" left clicked it: 1 essence + 2 sprouts

So only on: mature, left click it gives me a sprout. 

Hey that works for me for now. Now i at least know how to make backup sprouts.

I will attach a list of all the mods i use.

I'm on forge-1.10-12.18.0.2000

Hope it helps you. Good luck in finding it and thanx again for making such an awesome mod.

[Mods110.txt](https://github.com/xLionel775/AgriculturalExpansion/files/334644/Mods110.txt)

**Comment by MachinegunMarty** [comment]
Update:

Cleaned up my mod folder. 

Mods i didn't use i removed. Mods are all the latest versions now.

Some mods don't have 1.10 support yet, but still work.

Tested with the mod setup and still don't get a sprout, growing them mature and then left click still yields 2x sprout and 1 essence.

What i would want to know is if anybody else is having the same problem as me ?

I don't want you to put time in searching and troubleshooting a problem if it's only a problem on my side. 
could be that my world got corrupted somehow, saved some info somewhere that i don't know of i don't know. 

It doesn't spit out an error so, that doesn't help much.

I will test with only this mod installed and work my way up. Will get back on that.

Uploaded the updated mod list.

[mods110Updated.txt](https://github.com/xLionel775/AgriculturalExpansion/files/334986/mods110Updated.txt)

**Comment by MachinegunMarty** [comment]
Update:

With just your mod and reapermod i get sprouts when right clicking !

Will update this post with the result.

Found it !

It's Pam's HarvestCraft.
She hasn't updated to 1.10, but it works, except for this.

As soon as i added that the sprout dropping stopped.

So i tested if i could get both to work and the solution is:

In Pam's HarvestCrafts config file somewhere halfway under "General":

general {
    # Enables harvesting by right-clicking. [default: true]
    B:enableEasyHarvest=false 

Set enableEasyHarvest to false and now it works.

So as a final test:

I tested if it was a right click mod (reapermod) and Pam combo so....

I set EasyHarvest to true and removed reapermod.

Tested and no sprout drops.

So it's something wrong in pam's easy harvest.

I will report this to her and link her to this github (if that's ok with you ?)

Thanx for your patience and testing.

Hope you didn't put to much time in this problem.

I'm glad that we eventually found the problem and if anyone faces the same problem you can up this solution.

Good luck and thanx for your awesome mod.

keep up the good work !

grtz,

Machinegun_Marty

**Comment by ionelaipatioaei** [comment]
Ok, glad you solved the problem, by the way I have no problem with linking this github. 
Also thanks for figuring this out.
Issue Closed.
