### ISSUE TITLE
[1.10.2-1.2.0] Crafting nether ores crashes client in Forge 1.10.2 build 2026

### ISSUE THREAD

**Issue by kreezxil** [xLionel775/AgriculturalExpansion#14]
It doesn't happen when crafting ores from other dimensions like the overworld.

Client Crash Report: http://pastebin.com/9M0dY2zZ

The dedicated server doesn't crash at all and is unaffected.

**Comment by ionelaipatioaei** [comment]
Fixed in r-1.2.1.
Please leave a comment if the client crashes or not.
