### ISSUE TITLE
Ore Dict

### ISSUE THREAD

**Issue by DoughnutDev** [xLionel775/AgriculturalExpansion#15]
Can you please add Tin Sprout, Copper, Bronze, etc to use the oredict ingots?

**Comment by DoughnutDev** [comment]
Also I am using TechReborn and the Ruby seeds seem to have an issue with it making one with either a rubber or a ruby in the center to make a ruby sprout. I made some recipe tweaks to fix the oredict issue for now with Minetweaker http://hastebin.com/lajuxicupo.xml

**Comment by ionelaipatioaei** [comment]
I use OreDictionary for every recipe(input and output).
