### ISSUE TITLE
Dupe(?) bug when breaking non-mature crops.

### ISSUE THREAD

**Issue by BraynStorm** [xLionel775/AgriculturalExpansion#2]
Basically you can plant and break a crop without waiting for it to grow at all and sometimes you can get more than 1 seed.

`MC 1.9.4`
`Agricultural Expansion beta 1.1.7`
`Forge 1963`

**Comment by ionelaipatioaei** [comment]
I fix the bug in beta 1.1.9

**Comment by APolarBaer** [comment]
now it does it with essence
1.9.4

https://github.com/xLionel775/AgriculturalExpansion/issues/11
