### ISSUE TITLE
Suggestion Support Extreme Reactors

### ISSUE THREAD

**Issue by rigerc** [xLionel775/AgriculturalExpansion#20]
Extreme Reactors is a Big reactors port for 1.10 and it introduces several ores, most importantly yellorium :)

**Comment by DiscipleOfUrza** [comment]
I second this. Vibrant Alloy from EnderIO would also be worth adding as a top-tier sprout.

**Comment by ionelaipatioaei** [comment]
Extreme Reactors support will be added soon. Vibrant Alloy can be made using other raw materials.
