### ISSUE TITLE
Modded crops pop off of Fertilized Dirt from Random Things. 

### ISSUE THREAD

**Issue by xChitose** [xLionel775/AgriculturalExpansion#21]
Just as the title says, crops pop off of the soil.<br /><br />The soil, as far as I understand, apply random growth ticks at certain intervals, and when this happens, the crop will pop off into the world.<br /><br />Edit:<br /><br />This applies to modded crops, such as those present in Agcultural Expansion and Mystical Agriculture.<br /><br />Closing as it deals with Random Things.

Edit: 

Reopening.

**Comment by ionelaipatioaei** [comment]
Fixed in r-1.2.2.
