### ISSUE TITLE
Missing getPlantType override in AECrop

### ISSUE THREAD

**Issue by lumien231** [xLionel775/AgriculturalExpansion#22]
Connected to lumien231/Random-Things#114

The Plant Type of your item and your block are different.
You extend ItemSeeds with AESeed so the type of the item is EnumPlantType.Crop
You don't override IPlantable.getPlantType in AECrop so it defaults to EnumPlantType.Plains

That's why your seeds can be planted on random things fertilized dirt but get destroyed next "update" because the block (Which has a different plant type) can't stay there.

**Comment by ionelaipatioaei** [comment]
Fixed in r-1.2.2.
