### ISSUE TITLE
Gold/Iron Essence No Recipe

### ISSUE THREAD

**Issue by slidingmike** [xLionel775/AgriculturalExpansion#5]
Good morning.

Some users are reporting that the essence is reporting no crafting recipe via JEI as well as unable to craft via the documentation you have in curse forge. 

"-Iron Crop(4 essence = 2 iron; 8 essence = 4 iron);

-Gold Crop(4 essence = 2 gold; 8 essence = 4 gold);"

Forge version is 1268
Agricultural Expansion is beta 1.1.9
MC 1.9.4

**Comment by Gepett0** [comment]
No problems here using same versions (considering u meant forge 1968).
Any additional mods?

**Comment by slidingmike** [comment]
I was afraid you was going to say that. We actually have a pretty extensive mod list for the pack right now. (I believe 90 total loaded.)

Yes I did mean 1968.

I'll have my testers start breaking it down to see if we can identify the culprit since there's no issue on your side. Can we leave this open until then?

**Comment by ionelaipatioaei** [comment]
Do you still have this problem?

**Comment by slidingmike** [comment]
Crap, thought I posted yesterday. This was a result of "Unidict" unifying gold and iron ingots. Removing it from that config solved the problem.
