### ISSUE TITLE
Drop chances for sprouts through harvest are to high

### ISSUE THREAD

**Issue by Gepett0** [xLionel775/AgriculturalExpansion#6]
I have simple autofarm setup (enderio farming station).
Getting more sprouts than essences.

https://pl.vc/o64q4

Using lastest Beta 1.1.9

**Comment by ionelaipatioaei** [comment]
The bug was fixed in beta 1.1.12 which should be available in 10 minutes. Now the crop drop only 1 sprout and has a chance of 33% to drop another one and only 1 essence with a chance of 10% to drop another one.
