### ISSUE TITLE
[1.9.4] Dye essence Part 2

### ISSUE THREAD

**Issue by Gepett0** [xLionel775/AgriculturalExpansion#7]
Hi,

new problems with essences.
Now the recipe is 1 essence + 1 dye of color X giving 2 dyes of color X.
Intended or bug?

**Comment by ionelaipatioaei** [comment]
Intended. I decided to add this recipe for dye because if I use ShapedRecipe for this because https://github.com/xLionel775/AgriculturalExpansion/issues/4 bug doesn't disappear.
