### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by ghost** [xLionel775/AgriculturalExpansion#9]
I played a few minutes I went into a cave and everytime I look into the same corner, the Game stops for a second and crashes to the desktop. After restarting and rejoining in the world and allmost immediately after appearing in the world appearing the game crashes again. The crash log says ticking entity but there are no mobs to see and hear around me.
crash log: http://paste.ee/p/SwWHF

**Comment by ionelaipatioaei** [comment]
Fixed in beta 1.1.13-mc1.10.

**Comment by ghost** [comment]
Now I can continue playing my world thank you.
